// constants/presetElements.js

export const ELEMENT_CATEGORIES = [
  { id: 'all', label: 'All Elements' },
  { id: 'shapes', label: 'Shapes & Polygons' },
  { id: 'badges', label: 'Badges & Tags' },
  { id: 'cta', label: 'CTA Buttons' },
  { id: 'events', label: 'Events & Holidays' },
  { id: 'headers', label: 'Header Banners' },
  { id: 'cards', label: 'Feature Cards' },
  { id: 'contact', label: 'Contact & Social' },
  { id: 'containers', label: 'Glass Containers' },
  { id: 'bullets', label: 'Infographics & Lists' },
  { id: 'accents', label: 'Decorative Shapes' },
  { id: 'frames', label: 'Borders & Frames' }
];

export const TEXT_PRESETS = [
  {
    name: 'Header Banner',
    style: {
      bgColor: '#3B82F6',
      color: '#FFFFFF',
      fontSize: 22,
      fontWeight: '800',
      fontFamily: 'Bebas Neue',
      borderRadius: 8,
      textAlign: 'center',
      borderWidth: 0
    }
  },
  {
    name: 'Red Badge / CTA',
    style: {
      bgColor: '#EF4444',
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '800',
      fontFamily: 'Poppins',
      borderRadius: 99,
      textAlign: 'center',
      borderWidth: 0
    }
  },
  {
    name: 'Glassmorphism Box',
    style: {
      bgColor: 'rgba(255, 255, 255, 0.12)',
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
      fontFamily: 'Poppins',
      borderRadius: 12,
      borderColor: 'rgba(255, 255, 255, 0.3)',
      borderWidth: 1,
      textAlign: 'center'
    }
  },
  {
    name: 'Gold Accent Title',
    style: {
      bgColor: '#FEF08A',
      color: '#854D0E',
      fontSize: 20,
      fontWeight: '900',
      fontFamily: 'Montserrat',
      borderRadius: 6,
      borderColor: '#EAB308',
      borderWidth: 2,
      textAlign: 'center'
    }
  },
  {
    name: 'Dark Outline Pill',
    style: {
      bgColor: 'transparent',
      color: '#38BDF8',
      fontSize: 14,
      fontWeight: '700',
      fontFamily: 'Poppins',
      borderRadius: 99,
      borderColor: '#38BDF8',
      borderWidth: 2,
      textAlign: 'center'
    }
  },
  {
    name: 'Minimal Subtitle',
    style: {
      bgColor: 'transparent',
      color: '#94A3B8',
      fontSize: 15,
      fontWeight: '500',
      fontFamily: 'Roboto',
      borderRadius: 0,
      borderWidth: 0,
      textAlign: 'center'
    }
  }
];

export const PRESET_ELEMENTS = [
  // ==========================================
  // 0. BASIC SHAPES & POLYGONS (Canva Essentials)
  // ==========================================
  {
    id: 'shape-square-solid',
    category: 'shapes',
    name: 'Solid Square',
    type: 'badge',
    text: '',
    bgColor: '#3B82F6',
    borderWidth: 0,
    width: 200,
    height: 200,
    borderRadius: 0
  },
  {
    id: 'shape-circle-solid',
    category: 'shapes',
    name: 'Solid Circle',
    type: 'badge',
    text: '',
    bgColor: '#EF4444',
    borderWidth: 0,
    width: 200,
    height: 200,
    borderRadius: 9999
  },
  {
    id: 'shape-rounded-rect',
    category: 'shapes',
    name: 'Rounded Rectangle',
    type: 'badge',
    text: '',
    bgColor: '#10B981',
    borderWidth: 0,
    width: 260,
    height: 140,
    borderRadius: 16
  },
  {
    id: 'shape-pill',
    category: 'shapes',
    name: 'Pill Shape',
    type: 'badge',
    text: '',
    bgColor: '#8B5CF6',
    borderWidth: 0,
    width: 280,
    height: 100,
    borderRadius: 99
  },
  {
    id: 'shape-square-outline',
    category: 'shapes',
    name: 'Square Outline',
    type: 'badge',
    text: '',
    bgColor: 'transparent',
    borderColor: '#F59E0B',
    borderWidth: 4,
    width: 200,
    height: 200,
    borderRadius: 0
  },
  {
    id: 'shape-circle-outline',
    category: 'shapes',
    name: 'Circle Outline',
    type: 'badge',
    text: '',
    bgColor: 'transparent',
    borderColor: '#06B6D4',
    borderWidth: 4,
    width: 200,
    height: 200,
    borderRadius: 9999
  },

  // ==========================================
  // 1. BADGES & TAGS
  // ==========================================
  {
    id: 'badge-adm-open-1',
    category: 'badges',
    name: 'Red Admission Badge',
    type: 'badge',
    text: '🔥 ADMISSIONS OPEN 2026-27',
    bgColor: '#EF4444',
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    width: 240,
    height: 38,
    borderRadius: 99
  },
  {
    id: 'badge-adm-open-2',
    category: 'badges',
    name: 'Emerald Pill Tag',
    type: 'badge',
    text: '✔ REGISTRATION OPEN FOR CLASS N.C. TO XII',
    bgColor: '#10B981',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
    width: 290,
    height: 34,
    borderRadius: 99
  },
  {
    id: 'badge-result-100',
    category: 'badges',
    name: '100% Board Result Tag',
    type: 'badge',
    text: '🏆 100% BOARD RESULT GUARANTEED',
    bgColor: '#F59E0B',
    color: '#0F172A',
    fontSize: 12,
    fontWeight: '900',
    width: 270,
    height: 36,
    borderRadius: 8
  },
  {
    id: 'badge-iso-cert',
    category: 'badges',
    name: 'ISO Certified Tag',
    type: 'badge',
    text: '✨ ISO 9001:2015 CERTIFIED INSTITUTION',
    bgColor: '#3B82F6',
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    width: 250,
    height: 32,
    borderRadius: 6
  },
  {
    id: 'badge-limited-seats',
    category: 'badges',
    name: 'Limited Seats Alert',
    type: 'badge',
    text: '⚠️ LIMITED SEATS AVAILABLE',
    bgColor: '#DC2626',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
    width: 210,
    height: 34,
    borderRadius: 20
  },
  {
    id: 'badge-discount-early',
    category: 'badges',
    name: 'Early Bird Discount Tag',
    type: 'badge',
    text: '🎉 20% EARLY BIRD FEE DISCOUNT',
    bgColor: '#8B5CF6',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    width: 230,
    height: 36,
    borderRadius: 12
  },
  {
    id: 'badge-cbse-affil',
    category: 'badges',
    name: 'CBSE Affiliated Tag',
    type: 'badge',
    text: '🏫 CBSE AFFILIATED SCHOOL',
    bgColor: '#1E293B',
    borderColor: '#3B82F6',
    borderWidth: 2,
    color: '#60A5FA',
    fontSize: 11,
    fontWeight: '800',
    width: 210,
    height: 34,
    borderRadius: 8
  },
  {
    id: 'badge-no-donation',
    category: 'badges',
    name: 'Zero Admission Fee Badge',
    type: 'badge',
    text: '🎁 ZERO ADMISSION FEE THIS WEEK',
    bgColor: '#059669',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    width: 240,
    height: 36,
    borderRadius: 99
  },
  {
    id: 'badge-rank-1',
    category: 'badges',
    name: 'Rank #1 School Badge',
    type: 'badge',
    text: '🥇 RANKED #1 SCHOOL IN REGION',
    bgColor: '#D97706',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
    width: 230,
    height: 36,
    borderRadius: 8
  },
  {
    id: 'badge-smart-campus',
    category: 'badges',
    name: 'Smart Campus Badge',
    type: 'badge',
    text: '💡 100% DIGITAL SMART CAMPUS',
    bgColor: '#0284C7',
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    width: 220,
    height: 32,
    borderRadius: 99
  },
  {
    id: 'badge-scholarship-tag',
    category: 'badges',
    name: 'Scholarship Available Tag',
    type: 'badge',
    text: '🎓 UP TO 100% SCHOLARSHIP',
    bgColor: '#4F46E5',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
    width: 220,
    height: 36,
    borderRadius: 8
  },
  {
    id: 'badge-english-medium',
    category: 'badges',
    name: 'English Medium Tag',
    type: 'badge',
    text: '📚 ENGLISH MEDIUM CO-ED SCHOOL',
    bgColor: '#0F172A',
    borderColor: '#059669',
    borderWidth: 2,
    color: '#34D399',
    fontSize: 10,
    fontWeight: '800',
    width: 230,
    height: 32,
    borderRadius: 99
  },

  // ==========================================
  // 2. CTA BUTTONS & ACTIONS
  // ==========================================
  {
    id: 'cta-apply-now',
    category: 'cta',
    name: 'Apply Now Solid Red',
    type: 'badge',
    text: 'APPLY ONLINE NOW ➔',
    bgColor: '#E11D48',
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
    width: 200,
    height: 42,
    borderRadius: 10
  },
  {
    id: 'cta-call-us',
    category: 'cta',
    name: 'Call Us Now Green Pill',
    type: 'badge',
    text: '📞 CALL TODAY: {{phone}}',
    fieldBinding: 'phone',
    bgColor: '#16A34A',
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    width: 220,
    height: 40,
    borderRadius: 99
  },
  {
    id: 'cta-visit-campus',
    category: 'cta',
    name: 'Visit Campus Blue CTA',
    type: 'badge',
    text: '🏫 VISIT CAMPUS TODAY',
    bgColor: '#2563EB',
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    width: 210,
    height: 40,
    borderRadius: 8
  },
  {
    id: 'cta-whatsapp-us',
    category: 'cta',
    name: 'WhatsApp Us Emerald CTA',
    type: 'badge',
    text: '💬 WHATSAPP US FOR DETAILS',
    bgColor: '#059669',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    width: 220,
    height: 38,
    borderRadius: 99
  },
  {
    id: 'cta-book-seat',
    category: 'cta',
    name: 'Book Seat Amber CTA',
    type: 'badge',
    text: '⚡ BOOK YOUR SEAT NOW',
    bgColor: '#D97706',
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    width: 200,
    height: 42,
    borderRadius: 8
  },
  {
    id: 'cta-download-prospectus',
    category: 'cta',
    name: 'Download Prospectus Glass CTA',
    type: 'badge',
    text: '📥 DOWNLOAD PROSPECTUS',
    bgColor: 'rgba(255, 255, 255, 0.15)',
    borderColor: '#FFFFFF',
    borderWidth: 1.5,
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    width: 210,
    height: 38,
    borderRadius: 10
  },
  {
    id: 'cta-enquire-now',
    category: 'cta',
    name: 'Enquire Today Orange CTA',
    type: 'badge',
    text: '✉ ENQUIRE TODAY',
    bgColor: '#EA580C',
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    width: 180,
    height: 40,
    borderRadius: 8
  },
  {
    id: 'cta-location-link',
    category: 'cta',
    name: 'Get Directions CTA',
    type: 'badge',
    text: '📍 GET CAMPUS LOCATION',
    bgColor: '#4338CA',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    width: 200,
    height: 36,
    borderRadius: 99
  },
  {
    id: 'cta-scan-qr',
    category: 'cta',
    name: 'Scan QR Code CTA',
    type: 'badge',
    text: '📲 SCAN TO APPLY ONLINE',
    bgColor: '#0F172A',
    borderColor: '#38BDF8',
    borderWidth: 2,
    color: '#38BDF8',
    fontSize: 11,
    fontWeight: '800',
    width: 210,
    height: 38,
    borderRadius: 10
  },
  {
    id: 'cta-free-demo',
    category: 'cta',
    name: 'Free Demo Class CTA',
    type: 'badge',
    text: '🎓 ATTEND FREE DEMO CLASS',
    bgColor: '#7C3AED',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
    width: 220,
    height: 40,
    borderRadius: 99
  },

  // ==========================================
  // 3. EVENTS & HOLIDAYS
  // ==========================================
  {
    id: 'event-science-exhib',
    category: 'events',
    name: 'Annual Science Exhibition Banner',
    type: 'badge',
    text: '🔬 ANNUAL SCIENCE & TECH EXHIBITION 2026',
    bgColor: '#0284C7',
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    width: 320,
    height: 40,
    borderRadius: 8
  },
  {
    id: 'event-sports-meet',
    category: 'events',
    name: 'Annual Sports Day Banner',
    type: 'badge',
    text: '⚽ ANNUAL SPORTS MEET & ATHLETICS',
    bgColor: '#16A34A',
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    width: 300,
    height: 40,
    borderRadius: 8
  },
  {
    id: 'event-republic-day',
    category: 'events',
    name: 'Republic Day Celebration Tag',
    type: 'badge',
    text: '🇮🇳 HAPPY REPUBLIC DAY CELEBRATION',
    bgColor: '#EA580C',
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    width: 290,
    height: 38,
    borderRadius: 99
  },
  {
    id: 'event-indep-day',
    category: 'events',
    name: 'Independence Day Banner',
    type: 'badge',
    text: '🇮🇳 80th INDEPENDENCE DAY CELEBRATIONS',
    bgColor: '#059669',
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    width: 310,
    height: 40,
    borderRadius: 8
  },
  {
    id: 'event-ptm-meet',
    category: 'events',
    name: 'Parent Teacher Meeting Alert',
    type: 'badge',
    text: '👨‍👩‍👧 PARENT-TEACHER MEETING (PTM)',
    bgColor: '#D97706',
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    width: 280,
    height: 38,
    borderRadius: 8
  },
  {
    id: 'event-annual-function',
    category: 'events',
    name: 'Annual Day Cultural Fest',
    type: 'badge',
    text: '🎭 ANNUAL CULTURAL FEST & AWARDS NIGHT',
    bgColor: '#9333EA',
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    width: 320,
    height: 40,
    borderRadius: 12
  },
  {
    id: 'event-swachh-bharat',
    category: 'events',
    name: 'Swachh Bharat Drive Tag',
    type: 'badge',
    text: '🧹 SWACHH BHARAT ABHIYAN DRIVE',
    bgColor: '#0D9488',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    width: 260,
    height: 36,
    borderRadius: 99
  },
  {
    id: 'event-yoga-day',
    category: 'events',
    name: 'International Yoga Day',
    type: 'badge',
    text: '🧘 INTERNATIONAL YOGA DAY CELEBRATION',
    bgColor: '#65A30D',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    width: 290,
    height: 36,
    borderRadius: 99
  },
  {
    id: 'event-olympiad-winner',
    category: 'events',
    name: 'National Olympiad Winner',
    type: 'badge',
    text: '🏅 NATIONAL SCIENCE OLYMPIAD WINNERS',
    bgColor: '#B45309',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
    width: 290,
    height: 38,
    borderRadius: 8
  },
  {
    id: 'event-teachers-day',
    category: 'events',
    name: 'Teachers Day Gratitude Tag',
    type: 'badge',
    text: "💐 HAPPY TEACHERS' DAY CELEBRATION",
    bgColor: '#E11D48',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
    width: 280,
    height: 38,
    borderRadius: 99
  },
  {
    id: 'event-summer-camp',
    category: 'events',
    name: 'Summer Camp Workshop Tag',
    type: 'badge',
    text: '☀️ SUMMER CREATIVE CAMP 2026',
    bgColor: '#F59E0B',
    color: '#0F172A',
    fontSize: 12,
    fontWeight: '900',
    width: 260,
    height: 38,
    borderRadius: 10
  },
  {
    id: 'event-exam-wishes',
    category: 'events',
    name: 'Best Wishes for Board Exams',
    type: 'badge',
    text: '👍 BEST OF LUCK FOR BOARD EXAMS 2026',
    bgColor: '#2563EB',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    width: 280,
    height: 36,
    borderRadius: 8
  },

  // ==========================================
  // 4. HEADERS & TITLE BANNERS
  // ==========================================
  {
    id: 'hdr-bebas-bold',
    category: 'headers',
    name: 'Bebas Neue Display Header',
    type: 'text',
    text: 'BUILDING LEADERS OF TOMORROW',
    fontSize: 34,
    fontWeight: '900',
    fontFamily: 'Bebas Neue',
    color: '#FFFFFF',
    width: 440,
    height: 50,
    textAlign: 'center'
  },
  {
    id: 'hdr-school-title',
    category: 'headers',
    name: 'Dynamic School Name Header',
    type: 'text',
    text: '{{schoolName}}',
    fieldBinding: 'schoolName',
    fontSize: 30,
    fontWeight: '900',
    fontFamily: 'Bebas Neue',
    color: '#F8FAFC',
    width: 450,
    height: 48,
    textAlign: 'center'
  },
  {
    id: 'hdr-tagline-sub',
    category: 'headers',
    name: 'Dynamic School Tagline Subheader',
    type: 'text',
    text: '{{tagline}}',
    fieldBinding: 'tagline',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Poppins',
    color: '#93C5FD',
    width: 420,
    height: 32,
    textAlign: 'center'
  },
  {
    id: 'hdr-gold-gradient-text',
    category: 'headers',
    name: 'Excellence Title Accent',
    type: 'text',
    text: 'EXCELLENCE IN ACADEMICS & SPORTS',
    fontSize: 22,
    fontWeight: '800',
    fontFamily: 'Poppins',
    color: '#FBBF24',
    width: 440,
    height: 40,
    textAlign: 'center'
  },
  {
    id: 'hdr-neon-cyan',
    category: 'headers',
    name: 'Neon Cyan Headline',
    type: 'text',
    text: 'WELCOME TO SESSION 2026-27',
    fontSize: 26,
    fontWeight: '900',
    fontFamily: 'Montserrat',
    color: '#38BDF8',
    width: 440,
    height: 44,
    textAlign: 'center'
  },
  {
    id: 'hdr-curved-ribbon-bg',
    category: 'headers',
    name: 'Ribbon Box Header Title',
    type: 'badge',
    text: "🎓 SHAPE YOUR CHILD'S BRIGHT FUTURE",
    bgColor: '#312E81',
    color: '#818CF8',
    fontSize: 13,
    fontWeight: '800',
    width: 360,
    height: 44,
    borderRadius: 12
  },
  {
    id: 'hdr-minimal-dark',
    category: 'headers',
    name: 'Minimal Dark Header Label',
    type: 'text',
    text: 'ADM-2026 // OFFICIAL ANNOUNCEMENT',
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Roboto',
    color: '#94A3B8',
    letterSpacing: 2,
    width: 400,
    height: 28,
    textAlign: 'center'
  },
  {
    id: 'hdr-bold-red-banner',
    category: 'headers',
    name: 'Bold Red Header Block',
    type: 'badge',
    text: 'EXCLUSIVE ADMISSION NOTIFICATION',
    bgColor: '#991B1B',
    color: '#FEF2F2',
    fontSize: 14,
    fontWeight: '900',
    width: 380,
    height: 46,
    borderRadius: 6
  },
  {
    id: 'hdr-emerald-sub',
    category: 'headers',
    name: 'Emerald Tag Subheader',
    type: 'badge',
    text: 'CREATING A LEGACY OF ACADEMIC BRILLIANCE',
    bgColor: '#065F46',
    color: '#A7F3D0',
    fontSize: 11,
    fontWeight: '800',
    width: 350,
    height: 36,
    borderRadius: 99
  },
  {
    id: 'hdr-gradient-subtitle',
    category: 'headers',
    name: 'Gradient Style Subtext',
    type: 'text',
    text: 'Nurturing Curiosity • Inspiring Innovation • Achieving Dreams',
    fontSize: 13,
    fontWeight: '600',
    fontFamily: 'Poppins',
    color: '#E0E7FF',
    width: 460,
    height: 30,
    textAlign: 'center'
  },

  // ==========================================
  // 5. FEATURE CARDS & HIGHLIGHTS
  // ==========================================
  {
    id: 'card-smart-class',
    category: 'cards',
    name: 'Smart Classrooms Highlight',
    type: 'badge',
    text: '🖥️ Interactive Smart Classrooms',
    bgColor: '#1E293B',
    borderColor: '#38BDF8',
    borderWidth: 1.5,
    color: '#F8FAFC',
    fontSize: 12,
    fontWeight: '700',
    width: 240,
    height: 45,
    borderRadius: 12
  },
  {
    id: 'card-lab-facility',
    category: 'cards',
    name: 'Hi-Tech Labs Highlight',
    type: 'badge',
    text: '🔬 Modern Science & Computer Labs',
    bgColor: '#1E293B',
    borderColor: '#34D399',
    borderWidth: 1.5,
    color: '#F8FAFC',
    fontSize: 12,
    fontWeight: '700',
    width: 250,
    height: 45,
    borderRadius: 12
  },
  {
    id: 'card-sports-complex',
    category: 'cards',
    name: 'Sports Facilities Box',
    type: 'badge',
    text: '🏀 World Class Sports Complex',
    bgColor: '#1E293B',
    borderColor: '#FBBF24',
    borderWidth: 1.5,
    color: '#F8FAFC',
    fontSize: 12,
    fontWeight: '700',
    width: 240,
    height: 45,
    borderRadius: 12
  },
  {
    id: 'card-transport-fac',
    category: 'cards',
    name: 'GPS Transport Box',
    type: 'badge',
    text: '🚌 Safe GPS Bus Transportation',
    bgColor: '#1E293B',
    borderColor: '#F43F5E',
    borderWidth: 1.5,
    color: '#F8FAFC',
    fontSize: 12,
    fontWeight: '700',
    width: 240,
    height: 45,
    borderRadius: 12
  },

  // ==========================================
  // 6. CONTACT & SOCIAL INFO
  // ==========================================
  {
    id: 'contact-phone-block',
    category: 'contact',
    name: 'Dynamic Phone Line',
    type: 'text',
    text: '📞 {{phone}}',
    fieldBinding: 'phone',
    fontSize: 14,
    fontWeight: '800',
    fontFamily: 'Poppins',
    color: '#FFFFFF',
    width: 220,
    height: 32,
    textAlign: 'center'
  },
  {
    id: 'contact-email-block',
    category: 'contact',
    name: 'Dynamic Email Line',
    type: 'text',
    text: '✉️ {{email}}',
    fieldBinding: 'email',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Poppins',
    color: '#CBD5E1',
    width: 240,
    height: 28,
    textAlign: 'center'
  },
  {
    id: 'contact-address-block',
    category: 'contact',
    name: 'Dynamic Address Line',
    type: 'text',
    text: '📍 {{address}}',
    fieldBinding: 'address',
    fontSize: 11,
    fontWeight: '500',
    fontFamily: 'Roboto',
    color: '#94A3B8',
    width: 320,
    height: 36,
    textAlign: 'center'
  },
  {
    id: 'contact-website-block',
    category: 'contact',
    name: 'Dynamic Website Badge',
    type: 'badge',
    text: '🌐 {{website}}',
    fieldBinding: 'website',
    bgColor: 'rgba(15, 23, 42, 0.8)',
    borderColor: '#38BDF8',
    borderWidth: 1,
    color: '#38BDF8',
    fontSize: 11,
    fontWeight: '700',
    width: 220,
    height: 34,
    borderRadius: 99
  },

  // ==========================================
  // 7. GLASS CONTAINERS
  // ==========================================
  {
    id: 'container-glass-card',
    category: 'containers',
    name: 'Glassmorphism Backdrop Box',
    type: 'badge',
    text: '',
    bgColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    width: 380,
    height: 180,
    borderRadius: 16
  },
  {
    id: 'container-dark-card',
    category: 'containers',
    name: 'Solid Dark Section Container',
    type: 'badge',
    text: '',
    bgColor: '#0F172A',
    borderColor: '#1E293B',
    borderWidth: 2,
    width: 380,
    height: 200,
    borderRadius: 12
  },

  // ==========================================
  // 8. INFOGRAPHICS & LISTS
  // ==========================================
  {
    id: 'bullet-check-green',
    category: 'bullets',
    name: 'Green Check List Item',
    type: 'text',
    text: '✔ Experienced & Dedicated Faculty',
    fontSize: 13,
    fontWeight: '700',
    fontFamily: 'Poppins',
    color: '#10B981',
    width: 280,
    height: 28,
    textAlign: 'left'
  },
  {
    id: 'bullet-star-gold',
    category: 'bullets',
    name: 'Gold Star Highlight Item',
    type: 'text',
    text: '⭐ Individual Attention & Care',
    fontSize: 13,
    fontWeight: '700',
    fontFamily: 'Poppins',
    color: '#FBBF24',
    width: 260,
    height: 28,
    textAlign: 'left'
  },

  // ==========================================
  // 9. DECORATIVE SHAPES & ACCENTS
  // ==========================================
  {
    id: 'accent-divider-gold',
    category: 'accents',
    name: 'Gold Separator Line',
    type: 'badge',
    text: '',
    bgColor: '#F59E0B',
    width: 120,
    height: 4,
    borderRadius: 2
  },
  {
    id: 'accent-divider-cyan',
    category: 'accents',
    name: 'Cyan Neon Separator',
    type: 'badge',
    text: '',
    bgColor: '#06B6D4',
    width: 180,
    height: 3,
    borderRadius: 2
  },

  // ==========================================
  // 10. BORDERS & FRAMES
  // ==========================================
  {
    id: 'frame-border-gold',
    category: 'frames',
    name: 'Gold Outline Frame',
    type: 'badge',
    text: '',
    bgColor: 'transparent',
    borderColor: '#D97706',
    borderWidth: 2,
    width: 460,
    height: 460,
    borderRadius: 8
  },
  {
    id: 'frame-border-dashed',
    category: 'frames',
    name: 'Dashed Accent Frame',
    type: 'badge',
    text: '',
    bgColor: 'transparent',
    borderColor: '#38BDF8',
    borderWidth: 2,
    borderStyle: 'dashed',
    width: 440,
    height: 440,
    borderRadius: 16
  },
  {
    id: 'frame-border-square',
    category: 'frames',
    name: 'Square Border Frame',
    type: 'badge',
    text: '',
    bgColor: 'transparent',
    borderColor: '#38BDF8',
    borderWidth: 2,
    width: 440,
    height: 440,
    borderRadius: 0
  }
];